version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: developer
            MYSQL_PASSWORD: developer
    php:
        build: ./php5
        expose:
            - "9000"
        #xdebug
        ports:
            - "9001:9001"            
        volumes:
            - ./../code/www.myexample.com:/data/wwwroot/www.myexample.com
        links:
            - db
    nginx:
        image: nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./nginx/sample/conf.d:/etc/nginx/conf.d
            - ./nginx/sample/rewrite:/etc/nginx/rewrite
            - ./logs/nginx:/var/log/nginx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
         - PMA_HOST=db
        restart: always
        ports:
         - 8080:80
    node:
        build: ./node5
    redis:
        image: redis
        ports:
            - "6379:6379"
