version: '2'
services:
    application:
        build: .
        volumes:
            - ./symfony:/var/www/symfony
        tty: true
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    php:
        image: php:7.0-fpm
        expose:
            - "9000"
        volumes_from:
            - application
        tty: true
        links:
            - db
    nginx:
        image: nginx:1.9.14
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - application
        volumes:
	    - ./www.example.com:/data/wwwroot/www.example.com
	    - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/rewrite:/etc/nginx/rewrite
            - ./logs/nginx:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - application
            - php
            - nginx