version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: developer
            MYSQL_PASSWORD: developer
    php:
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ./code/www.example.com:/data/wwwroot/www.example.com
        links:
            - db
    nginx:
        image: nginx:1.9.14
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/rewrite:/etc/nginx/rewrite
            - ./logs/nginx:/var/log/nginx